# Default values for acceleration-calc.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

nameOverride: "acceleration-calc"
fullnameOverride: "acceleration-calc"


image:
  repository: acceleration-calc
  tag: latest
  pullPolicy: Never

service:
  type: NodePort
  port: 3000

urls:
  dv_url: "http://acceleration-dv:3001/dv"
  a_url: "http://acceleration-a:3002/a"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: join.local
      paths: [/calc]

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
