apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "acceleration-calc.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "acceleration-calc.name" . }}
    helm.sh/chart: {{ include "acceleration-calc.chart" . }}
    app.kubernetes.io/instance: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "acceleration-calc.name" . }}
      app.kubernetes.io/instance: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "acceleration-calc.name" . }}
        app.kubernetes.io/instance: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: "WEB_PORT"
              value: "{{ .Values.service.port }}"
            - name: "DV_URL"
              value: "{{ .Values.urls.dv_url }}"
            - name: "A_URL"
              value: "{{ .Values.urls.a_url }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
              initialDelaySeconds: 5
              periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
              initialDelaySeconds: 5
              periodSeconds: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
